Juegos/Juegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('admin/', admin.site.urls),
    path('', include('Smash.urls'))
]

admin.site.site_header = "Administración Smash"
admin.site.index_title = "Smash"

Juegos/Smash/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
app_name = 'Smash'

#Urls del proyecto y la vista correspondiente de donde esta el metodo de redireccion
urlpatterns = [
    url('registrar', views.registrar, name='registrar'),
    url('login', views.login_usuario, name='login'),
    url('logout', views.logout_usuario, name='logout'),
    url('galeria', views.galeria, name='galeria'),
    url('contacto', views.contacto, name='contacto'),
    url('listar_noticias', views.listar_noticias, name='listar_noticias'),
    path('eliminar_noticia/<id>/', views.eliminar_noticia, name='eliminar_noticia'),
    url('', views.index , name='index'),
]

Juegos/Smash/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

#Modelo antiguo para prueba que tenia foto y campos de autenticazion
class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    foto_perfil = models.ImageField(upload_to='foto_perfil', blank=True)

    def __str__(self):
        return self.user.username

#Modelo para subir las imagenes y mostrarlas en la galeria
class Image(models.Model):
    nombre = models.CharField(max_length=500)
    imagen = models.ImageField(upload_to='img', height_field=None, width_field=None)

    def __str__(self):
        return self.nombre

#Modelo nuevo para usuario segun rubrica
class Usuario(models.Model):
    nombre_usuario = models.CharField(max_length=50)
    clave = models.CharField(max_length=50)
    nombre_completo = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to='foto_usuarios', blank=True)
    fecha_registro = models.DateField(auto_now_add=True)
    estado_actual = models.CharField(max_length=50)
    cargo = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre_usuario

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

#Modelo para las noticias que se despliegan en listar_noticias
class Noticia(models.Model):
    titulo_noticia = models.CharField(max_length=50) 
    descripcion = models.CharField(max_length=1000)
    
    def __str__(self):
        return self.titulo_noticia

Juegos/Smash/forms.py
#Imports necesarios de nuestro proyecto
from django import forms
from django.contrib.auth.models import User
from .models import Noticia, Usuario

#Form para el registro de usuarios
class RegistrarForm(forms.ModelForm):
    clave = forms.CharField(widget=forms.PasswordInput(), label='Contraseña')
    class Meta:
        model = Usuario
        fields = ('nombre_usuario', 'clave', 'nombre_completo', 'estado_actual', 'cargo', 'imagen')

        #Remplazar los nombres de los fields con las labels que queramos
        labels = {
            'nombre_usuario' : 'Nombre de Usuario',
            'nombre_completo' : 'Nombre Completo',
            'clave' : 'Contraseña',
            'estado_actual' : 'Estado Actual',
            'cargo' : 'Cargo',
            'imagen' : 'Foto de Perfil'
        }

        #Ingresar textos de ayuda para llenado
        help_texts = {
            'nombre_usuario' : '',
        }

        #mensajes de error
        error_messages = {
            'nombre_usuario' : {
                'max_length': 'Maximo 150 caracteres',
                'required': 'Requerido'
            },
            'clave' : {
                'required': 'Requerido'
            },
        }

    #Constructor del formulario , le cambiamos la clase a form-control
    def __init__(self, *args, **kwargs):
        super(RegistrarForm, self).__init__(*args, **kwargs)
        self.fields['nombre_usuario'].widget.attrs.update({'class': 'form-control'})
        self.fields['nombre_completo'].widget.attrs.update({'class': 'form-control'})
        self.fields['clave'].widget.attrs.update({'class': 'form-control'})
        self.fields['estado_actual'].widget.attrs.update({'class': 'form-control'})
        self.fields['cargo'].widget.attrs.update({'class': 'form-control'})
        

Juegos/Smash/views.py
#renderizar cualquier template que creemos
from django.shortcuts import render, redirect

#para desplegar mensajes
from django.contrib import messages

#formas de autenticar y login de django
from django.contrib.auth import authenticate, login, logout

#redireccion a paginas mediante string
from django.http import HttpResponseRedirect, HttpResponse

#llamar urls usando el nombre de la url
from django.urls import reverse

#los forms que creamos en forms.py
from .forms import RegistrarForm

#los modelos que necesitemos
from .models import Noticia, Usuario

#redireccion a index despues de hacer logout
def logout_usuario(request):
    logout(request)
    return HttpResponseRedirect(reverse('Smash:index'))

#pagina principal
def index(request):
    return render(request, 'Smash/index.html', {})

#pagina de la galeria
def galeria(request):
    return render(request, 'Smash/galeria.html', {})

#pagina de contacto
def contacto(request):
    return render(request, 'Smash/contacto.html', {})

#Login usuario
def login_usuario(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('Smash:index'))
    else:
        if request.method == 'POST':
            #obtener campos desde el formulario y los asigno a las variables username y password
            username = request.POST.get('username')
            password = request.POST.get('password')
            #y lo autenticamos, si es que funciona devuelve el objeto y si no lo devuelve vacio
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('Smash:index'))
                else:
                    return HttpResponse("Tu cuenta esta inactiva")
            else:
                return HttpResponse("Datos invalidos")
        else:
            return render(request, 'Smash/login.html')

#Registrar usuario
def registrar(request):
    registrado = False
    if request.method == 'POST':
        #Obtengo la informacion desde el formulario y la paso a las variables user_form
        user_form = RegistrarForm(data=request.POST)
        if user_form.is_valid():
            #user_form.save lo guarda directamente en la base de datos
            usuario = user_form.save(commit=False)
            #Y si es que existe la imagen se le asigna al usuario
            if 'imagen' in request.FILES:
                usuario.foto_perfil = request.FILES['imagen']
            usuario.save()
            registrado = True
        else:
            return HttpResponse("Datos invalidos")
    else:
        user_form = RegistrarForm()

    return render(request, 'Smash/registrar.html',
        {'user_form': user_form,
         'registrado': registrado})


#Crud noticias juegos
#Listar Noticias
def listar_noticias(request):
    noticias = Noticia.objects.all()
    return render(request, 'Smash/listar_noticias.html', {'noticias':noticias})

#Eliminar Noticias
def eliminar_noticia(request, id):
    noticia = Noticia.objects.get(id=id)

    try:
        noticia.delete()
        mensaje = "Eliminado correctamente"
        messages.success(request, mensaje)
    except:
        mensaje = "Error al eliminar"
        messages.error(request, mensaje)

    return redirect('Smash:listar_noticias')

Juegos/Smash/templates/Smash/contacto.html
{% extends 'base.html' %}
{% block content %}
<html>
  <head>
      <title>Contacto</title>
      <link rel="stylesheet" href="css/style.css" type="text/css">
      <link rel="shortcut icon" href="img/logo.png" />
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!--Llamado a CDN Boostrap y sus bibliotecas-->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <!-- Fin CDN -->
      <!--Boton Buscar Script-->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
      <!--Fin buscar-->
      <!--Link Flexbox-->
      <link rel="stylesheet" type="text/css" href="css/flexboxgrid.css">
        <!--llamamos a  las font family de Google a utilizar en la pagina-->
        <link href="https://fonts.googleapis.com/css?family=Abel|Dancing+Script|Indie+Flower|Pacifico&display=swap" rel="stylesheet">
        <!--Fin Google Font-->

  </head>
  <body>
          <!--fin buscar-->
      </div>
      <!--Fin contacto barra superior-->
      <form class="container justify-content-center">
          <div class="form-group container-small">
            <label>Email</label>
            <input type="email" class="form-control" placeholder="Direccion de Correo Electronico">
            <small class="form-text text-muted">Solo para fines de contacto.</small>
          </div>
          <div class="form-group container-small">
              <label>Telefono</label>
              <input type="tel" class="form-control" placeholder="+56987654321">
            </div>
          <div class="form-group container-small">
            <label>Nombre</label>
            <input type="text" class="form-control" placeholder="Nombre">
          </div>
          <div class="form-group container-small">
              <label >Comentarios</label>
              <textarea class="form-control" rows="4" cols="20" placeholder="Sugerencias, reclamos o comentarios."></textarea>
            </div>
          <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-primary">Enviar</button>
          </div>
      </form>
      </body>
{% endblock content %}
</html>

Juegos/Smash/templates/Smash/galeria.html
{% extends 'base.html' %}
{% load static %}

<html>
    {% block head %}
    <head>
        <title>Galeria</title>
    </head>
    {% endblock head %}
    {% block content %}
    <body class="">
        <div class="row mb-3">
            <div class="col-lg-3 col-md-4 col-sm-6 ">
                <div class="card" style="width: 21rem; height: 0 auto;">
                    <img class="card-img-top"  src = "{{'static/img/Terry.jfif'}}" alt="chrom">
                    <div class="card-body">
                        <h5 class="card-title">Terry Bogard</h5>
                        <p class="card-text">King of Fighters trae su estilo de pelea</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="card" style="width: 21rem; height: 0 auto;">
                    <img class="card-img-top" src = "{{'static/img/banjo2.png'}}" alt="banjo2">
                    <div class="card-body">
                        <h5 class="card-title">Banjo Kazooie</h5>
                        <p class="card-text">Llegan a causar chaos</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="card" style="width: 21rem; height: 0 auto;">
                    <img class="card-img-top" src = "{{'static/img/fanart1.jpg'}}" alt="fan1">
                    <div class="card-body">
                        <h5 class="card-title">FanArt Destacado</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6">
                <div class="card" style="width: 21rem; height: 0 auto;">
                    <img class="card-img-top" src = "{{'static/img/fanart2.jpg'}}" alt="fan2">
                    <div class="card-body">
                        <h5 class="card-title">FanArt</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-3">
                <div class="card" style="width: 21rem; height: 0 auto;">
                    <img class="card-img-top" src = "{{'static/img/hero.jpg'}}" alt="hero">
                    <div class="card-body">
                        <h5 class="card-title">The Hero</h5>
                        <p class="card-text">Dragon quest se une al repertorio de juegos</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card" style="width: 21rem;">
                    <img class="card-img-top" src = "{{'static/img/incine.jpg'}}" alt="incine">
                    <div class="card-body">
                        <h5 class="card-title">Incineroar</h5>
                        <p class="card-text">Nuevo pokemon se une a la lucha</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card" style="width: 21rem;">
                    <img class="card-img-top" src = "{{'static/img/joker.png'}}" alt="joker">
                    <div class="card-body">
                        <h5 class="card-title">Joker</h5>
                        <p class="card-text">Se une para robarse el escenario</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card" style="width: 21rem;">
                    <img class="card-img-top" src = "{{'static/img/ridley.jpg'}}" alt="ridley">
                    <div class="card-body">
                        <h5 class="card-title">Ridley</h5>
                        <p class="card-text">despues de años porfin es jugable</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-3">
                <div class="card" style="width: 21rem;">
                    <img class="card-img-top" src = "{{'static/img/simon.jpg'}}" alt="simon">
                    <div class="card-body">
                        <h5 class="card-title">Simon</h5>
                        <p class="card-text">Los belmont traen sus trucos a la batalla</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card" style="width: 21rem;">
                    <img class="card-img-top" src = "{{'static/img/SSB.jpg'}}" alt="SSB">
                    <div class="card-body">
                        <h5 class="card-title">Arte Personajes Smash</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card" style="width: 21rem;">
                    <img class="card-img-top" src = "{{'static/img/piranha.jpg'}}" alt="piranha">
                    <div class="card-body">
                        <h5 class="card-title">Piranha Plant</h5>
                        <p class="card-text">Sakurai demostrando que todo peude ser un personaje</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card" style="width: 21rem;">
                    <img class="card-img-top" src = "{{'static/img/megaman.jpg'}}" alt="chrom">
                    <div class="card-body">
                        <h5 class="card-title">Megaman</h5>
                        <p class="card-text">Vuelve el software favorito de todos</p>
                    </div>
                </div>
            </div>
        </div>
        </body>
        {% endblock content %}
</html>

Juegos/Smash/templates/Smash/index.html
{% extends 'base.html' %}
{% load static %}
    
<html>

    <link href="..\..\static\Smash\estilo.css" rel="stylesheet" >
    {% block head %}
    <title>Smash!</title>
    {% endblock head %}
    {% block content %}
    <body>
    <!--banner-->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            
            <!-- Wrapper for slides -->
            <div class="carousel-inner" >
                <div class="item active">
                <img class="img-responsive center-block" alt="Imagen" src = "{{'static/img/chrome.jpg'}}" alt="Chrome" width="640px" height="480px">
                </div>
            
                <div class="item">
                <img class="img-responsive center-block" alt="Imagen" src = "{{'static/img/joker.png'}}" alt="Joker" width="640px" height="480px">
                </div>
            
                <div class="item">
                <img class="img-responsive center-block" alt="Imagen" src = "{{'static/img/Ridley.jpg'}}" alt="Ridley" width="640px" height="480px" >
                </div>
            </div>
            
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Anterior</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Siguiente</span>
            </a>
            </div>
    <!--Fin-->
    <!--Inicio Barra Titulo-->
    
    <!--Fin Barra titulo-->
    <!--Inici Contenido Texto-->
    <div>
        <div class="container-fluid">
            <div class="col-xs-12 col-lg-6">
                <h2 class="Texto">Banjo Kazooie</h2>
                <p class="Parrafo">El pase de temporada de Super Smash Bros. Ultimate se actualiza con un nuevo personaje, Banjo y Kazooie, que viene acompañado de los movimientos más singulares y especiales de su juego. Este iconico personaje de la compañia Rare ( misma compañia que desarrollo los juegos de donkey kong country) se une como uno de los personajes mas esperados entre los fanaticos del juego</p>
            </div>
            <div class="col-xs-12 col-lg-6 center-lg center-xs">
                <img class="paddingTop paddingBottom mt-3" src = "{{'static/img/Banjo.jpeg'}}" alt="banjo" width="100%">
            </div>
            
        </div>
        <hr>
        <div class="container-fluid">
            <div class="col-xs-12 col-lg-6 center-lg center-xs">
                <img class="paddingTop paddingBottom mt-3" src = "{{'static/img/ver5.jpg'}}" alt="verion 5" width="100%">
            </div>
            <div class="col-xs-12 col-lg-6">
                <h2 class="Texto">Super Smash Bros. Ultimate - Actualización versión 5.0.0</h2>
                <p class="Parrafo">Ajustes a luchadores y objetos, todo lo que necesitas saber en el siguiente <a href="https://es-americas-support.nintendo.com/app/answers/detail/a_id/45606/~/super-smash-bros.-ultimate---actualizaci%C3%B3n-versi%C3%B3n-5.0.0%3A-ajustes-de-luchadores">link</a></p>
            </div>
        </div>
        <hr>
        <div class="container-fluid">
            
            <div class="col-xs-12 col-lg-6">
                <h2 class="Texto">Terry Bogard</h2>
                <p class="Parrafo">Terry Bogard, de la serie FATAL FURY, se une al plantel de Super Smash Bros. Ultimate… En una presentación retransmitida en directo, Masahiro Sakurai, el director de Super Smash Bros. Ultimate, ha mostrado con todo detalle el nuevo luchador. El pack del aspirante 4: Terry Bogard ya está disponible, tanto como parte del Fighters Pass de Super Smash Bros. Ultimate, como en forma de set por separado.</p>
            </div>
            <div class="col-xs-12 col-lg-6 center-lg center-xs">
                <img class="paddingTop paddingBottom mt-3 mb-3" src = "{{'static/img/Terry.jfif'}}" alt="Terry" width="100%">
            </div>
        </div>
    </div>
</body>   
    <!--Fin Contenido Texto-->
    {% endblock content %}
</html>
    

Juegos/Smash/templates/Smash/listar_noticias.html
{% extends "base.html" %}

{% block content %}

<table>
    <tr>
        <th>Titulo</th>
        <th>Descripcion</th>
        <th>Opciones</th>
    </tr>

    {% for a in noticias %}
    <tr>
        <td>{{ a.titulo_noticia }}</td>
        <td>{{ a.descripcion }}</td>
        <td>
        <a href="{% url 'Smash:eliminar_noticia' a.id %}">Eliminar</a>
        </td>
    </tr>
    {% endfor %}
</table>

{% if messages %}

    {% for m in messages%}
    <div>{{ m }}</div>
    {% endfor %}

{% endif %}
{% endblock content %}

Juegos/Smash/templates/Smash/login.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link href="{% static 'Smash/estilo.css' %}" rel="stylesheet" >
    <title>Login Usuario</title>

{% endblock head %}
{% block content %}

<div class="login">
    <h1 class="text-center">Iniciar Sesion</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form_group col-lg-12 text-center">
            <label for="username">Username:</label>
            <input type="text" class="form_control" name="username" placeholder="Nombre de usuario">
        </div>
        <div class="form_group text-center">
            <label for="password">Password:</label>
            <input type="password" class="form_control" name="password" placeholder="Password">
        </div>
        <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary">Iniciar Sesion</button>
        </div>
    </form>
</div>
{% endblock content %}

Juegos/Smash/templates/Smash/registrar.html
{% extends 'base.html' %}
{% block head %}
    <title>Registro</title>
{% endblock head %}

{% block content %}
    <!--Jumbotron es el estilo de fondo gris que abarca todo los campos-->
    <div class="jumbotron">
        <!--Preguntar si el usuario ya termino el registro-->
        <!--Si es que ya termino, registrado es true y muestra el mensaje-->
        {% if registrado %}
            <h1>Registro exitoso</h1>
        <!--Si es que no esta registrado, muestra los formularios user_form y profile_form para que sean completados-->
        {% else %}
            <h1>Registro</h1>
            <h3>Ingrese los siguientes datos</h3>
            <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <!--Form definido en el forms.py junto con views.py-->
            {{ user_form.as_p }}
            <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        {% endif %}
    </div>
{% endblock content %}

Juegos/Smash/templates/Smash/subir.html
{% extends 'base.html' %}
{% block head %}
    <title>Subir Imagen</title>
{% endblock head %}

{% block content %}
    <!--Jumbotron es el estilo de fondo gris que abarca todo los campos-->
    <div class="jumbotron">
        <h1>Subir Imagenes</h1>
        <h3>Ingrese el nombre y la imagen</h3>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ image_form.as_p }}
            <button type="submit" class="btn btn-primary">Subir</button>
        </form>
    </div>
{% endblock content %}

Juegos/Smash/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Smash!</title>
    <link rel="shortcut icon" href="img/logo.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Llamado a CDN Bootstrap y sus bibliotecas-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <!--font family de Google a utilizar en la pagina-->
    <link href="https://fonts.googleapis.com/css?family=Abel|Dancing+Script|Indie+Flower|Pacifico&display=swap" rel="stylesheet">
</head>

<body>
    <div class="container-fluid" style="position: relative; min-height: 100vh;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'Smash:index' %}">
             <img src = "{{'static/img/logo.png'}}" width="30" height="30" class="d-inline-block" alt="logo"> Smash!</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse">
                <!--Barra de navegacion-->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'Smash:contacto' %}">Contacto</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'Smash:galeria' %}">Galeria</a></li>
                    <!--Preguntar si el usuario esta autenticado para desplegar menu correspondiente-->
                    <!--Si es que no esta logeado, despliega iniciar sesion y registrar-->
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'Smash:login' %}">Iniciar Sesion</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'Smash:registrar' %}">Registrar</a></li>
                    <!--Si esta logeado, despliega logout-->
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'Smash:listar_noticias' %}">Noticias</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'Smash:logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container-fluid">
            {% block content %}
            
            {% endblock content %}
        </div>
        <footer>
            <div class="footer pt-5">
                <p style="font-family: pasifico,cursive; background-color: rgba(0,0,0,0.5); text-align: center; width: auto;height: auto; position: absolute; left: 0; bottom: 0; width: 100%; color: white; background-color: gray;">Todos los derechos Reservados. <strong>SMASH 2019</strong></p>
            </div>
        </footer>
    </div>
</body>